### ISSUE TITLE
QuerySingle does not return anything(not even NULL) when not matched

### ISSUE THREAD

**Issue by pekkatki** [FrendsPlatform/Frends.Json#14] opened 2020-02-13 08:34 UTC
Case: some json elements are present based on certain conditions.
When doing a query with Frends.Json.Json.QuerySingle (1.1.35) and no such element is found from the json structure(option "Error when not matched" = false), the task returns nothing.

See image below. There is **no #result** to be found. Not even a null value.
This causes a problem when trying to e.g. in excl decision to find out whether the result was null or empty:
!string.IsNullOrEmpty(#result[Json.QuerySingleTask].ToString()) causes an error: "Cannot perform runtime binding on a null reference" 

![image](https://user-images.githubusercontent.com/15087821/74415427-06653b00-4e4c-11ea-803a-83d2047c21ae.png)

**Comment by EkiH** [comment] 2020-02-13 10:17
The error seems to be actually caused by 
> #Result[Json.QuerySingleTask] 

being null and then being called by .ToString()
This was fixed by changing to 

> !string.IsNullOrEmpty((string)#Result[Json.QuerySingleTask]?.ToString())

which handles the null value. Closing this as a non-issue

**Closed as completed by EkiH** 2020-02-13 10:17 UTC
